name: Java

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      java-version:
        type: string
        default: "25"
      command:
        type: string
        default: "./mvnw -B verify"

permissions:
  contents: read

jobs:
  java:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven
          cache-dependency-path: ${{ inputs.working-directory }}/pom.xml
      - name: Build e testes
        env:
          COMMAND: ${{ inputs.command }}
        run: $COMMAND
